import 'package:drift/drift.dart';

/// Represents a patient registered in the app.
/// Referenced by medications, reminders, and adherence_logs via patient_id.
class Patients extends Table {
  // Primary key — auto-incremented integer
  IntColumn get id => integer().autoIncrement()();

  // Registration code used during onboarding (from the clinic)
  TextColumn get registrationCode => text().named('registration_code')();

  // Full name
  TextColumn get fullName => text().named('full_name')();

  // Phone number — used for SMS fallback reminders
  TextColumn get phoneNumber => text().named('phone_number')();

  // Date of birth — stored as ISO 8601 string (yyyy-MM-dd)
  TextColumn get dateOfBirth => text().named('date_of_birth')();

  // Gender: 'male' | 'female' | 'other'
  TextColumn get gender => text().withLength(min: 1, max: 10)();

  // Preferred language: 'en' | 'zu' | 'xh'
  TextColumn get language => text().withDefault(const Constant('en'))();

  // PIN stored as a bcrypt hash — never store plain text
  TextColumn get pinHash => text().named('pin_hash')();

  // Caregiver phone number — nullable, only set if caregiver is linked
  TextColumn get caregiverPhone =>
      text().named('caregiver_phone').nullable()();

  // Caregiver relationship label — e.g. 'Mother', 'Spouse / Partner'
  TextColumn get caregiverRelationship =>
      text().named('caregiver_relationship').nullable()();

  // Risk level: 'low' | 'medium' | 'high' — recalculated by risk engine
  TextColumn get riskLevel =>
      text().named('risk_level').withDefault(const Constant('low'))();

  // 5-digit activation code generated by the worker during registration.
  // Null for patients created before this feature or via direct import.
  TextColumn get activationCode =>
      text().named('activation_code').nullable()();

  // Whether the patient has activated their account with the activation code.
  BoolColumn get isActivated =>
      boolean().named('is_activated').withDefault(const Constant(false))();

  // When the patient completed activation (entered code + set PIN).
  DateTimeColumn get activatedAt =>
      dateTime().named('activated_at').nullable()();

  // Comma-separated medical conditions e.g. "HIV,TB,Hypertension".
  TextColumn get conditions => text().nullable()();

  // ── Risk summary fields — updated by RiskEngine after every dose log ─────────

  // 0–100 numeric risk score (higher = riskier). Null until first calculation.
  IntColumn get riskScore => integer().named('risk_score').nullable()();

  // Adherence percentage over the last 30 days (0.0–100.0 scale).
  RealColumn get adherencePercentage30Days =>
      real().named('adherence_percentage_30d').nullable()();

  // Raw counts for the 30-day window.
  IntColumn get takenDoses30Days => integer().named('taken_doses_30d').nullable()();
  IntColumn get missedDoses30Days => integer().named('missed_doses_30d').nullable()();

  // When the most recent adherence log was recorded for this patient.
  DateTimeColumn get lastAdherenceLogAt =>
      dateTime().named('last_adherence_log_at').nullable()();

  // Clinic name — set when a worker registers the patient; used for filtering.
  TextColumn get clinicName => text().named('clinic_name').nullable()();

  // Whether the patient record has been synced to the backend
  BoolColumn get isSynced =>
      boolean().named('is_synced').withDefault(const Constant(false))();

  // Timestamps
  DateTimeColumn get createdAt => dateTime()
      .named('created_at')
      .withDefault(currentDateAndTime)();

  DateTimeColumn get updatedAt => dateTime()
      .named('updated_at')
      .withDefault(currentDateAndTime)();
}