// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvu28aQXr3Z6b7G9LiGX9nV5_7jRNih-8',
    appId: '1:840559421658:web:9947ef3b3c88019d841de3',
    messagingSenderId: '840559421658',
    projectId: 'med-adhere-app',
    authDomain: 'med-adhere-app.firebaseapp.com',
    storageBucket: 'med-adhere-app.firebasestorage.app',
    measurementId: 'G-N715PDBCP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKSIum7wQQEUq1q34_Ku0E326R2xEkzI',
    appId: '1:840559421658:android:10f705d6b01c6bfd841de3',
    messagingSenderId: '840559421658',
    projectId: 'med-adhere-app',
    storageBucket: 'med-adhere-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5c2On8q8gKcJ15il30YqLqAi8cWjxWwE',
    appId: '1:840559421658:ios:3c998e825ef3e322841de3',
    messagingSenderId: '840559421658',
    projectId: 'med-adhere-app',
    storageBucket: 'med-adhere-app.firebasestorage.app',
    iosBundleId: 'com.example.mzansiMedsReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5c2On8q8gKcJ15il30YqLqAi8cWjxWwE',
    appId: '1:840559421658:ios:3c998e825ef3e322841de3',
    messagingSenderId: '840559421658',
    projectId: 'med-adhere-app',
    storageBucket: 'med-adhere-app.firebasestorage.app',
    iosBundleId: 'com.example.mzansiMedsReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvu28aQXr3Z6b7G9LiGX9nV5_7jRNih-8',
    appId: '1:840559421658:web:87e1d0e9ba06677d841de3',
    messagingSenderId: '840559421658',
    projectId: 'med-adhere-app',
    authDomain: 'med-adhere-app.firebaseapp.com',
    storageBucket: 'med-adhere-app.firebasestorage.app',
    measurementId: 'G-Z5GQX9PTZ4',
  );
}
